[build]
  # No build command needed for static HTML files
  publish = "."

# Force HTTPS redirect
[[redirects]]
  from = "http://sherpaeconomy.com/*"
  to = "https://sherpaeconomy.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.sherpaeconomy.com/*"
  to = "https://sherpaeconomy.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.sherpaeconomy.com/*"
  to = "https://sherpaeconomy.com/:splat"
  status = 301
  force = true

[[redirects]]
  # Redirect root to landing page
  from = "/"
  to = "/sherpa-economy-landing.html"
  status = 200

[[redirects]]
  # Redirect /assessment to assessment page
  from = "/assessment"
  to = "/sherpa-assessment.html"
  status = 200

[[redirects]]
  # Redirect /speaking to speaking page
  from = "/speaking"
  to = "/speaking.html"
  status = 200

[[redirects]]
  # Redirect /consulting to consulting page
  from = "/consulting"
  to = "/consulting.html"
  status = 200

[[headers]]
  # Security headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Enable form handling for any forms in your HTML
[build.environment]
  NODE_VERSION = "18"
